using PoLaKoSz.Portfolio.Models;
using System;
using System.Collections.Generic;

namespace PoLaKoSz.Portfolio.Tests.Integration.StaticResources.Stocks
{
    class EurHuf
    {
        public static ForeignCurrency Get()
        {
            var stock = new Stock(
                isStarted: true,
                tickerID: "P_EURHUFX",
                ticker: "EURHUF=X",
                type: 2,
                fullName: "eurhufcomp",
                prefix: "FX",
                currency: "HUF",
                isin: "EU0006169864",
                name: "EUR/HUF",
                shortName: "EUR/HUF",
                chartName: "EUR/HUF",
                decimals: 2,
                forgDecimals: 1,
                open: 323.33,
                close: 323.45,
                last: 323.36,
                lastHTML: "323.358",
                lastSize: 1,
                lastTime: DateTimeOffset.FromUnixTimeSeconds(1561052014).UtcDateTime,
                lastHtmlTime: DateTimeOffset.FromUnixTimeSeconds(1561052014).UtcDateTime,
                change: -0.09,
                changePercentage: -0.03,
                min: 322.979,
                max: 324.352,
                bid: 11690,
                bidSize: 418,
                bidNum: 3,
                bidComp: 0,
                ask: 11700,
                askSize: 938,
                askNum: 6,
                askComp: 0,
                bid5: 11690,
                bid5Date: DateTimeOffset.FromUnixTimeSeconds(1561381646).UtcDateTime,
                bid5Size: 418,
                bid5Num: 3,
                bid5Comp: 0,
                ask5: 11700,
                ask5Date: DateTimeOffset.FromUnixTimeSeconds(1561381682).UtcDateTime,
                ask5Size: 938,
                ask5Num: 6,
                ask5Comp: 0,
                dealsCount: 2,
                deals: new List<StockDeal>()
                {
                    new StockDeal(29647, new DateTime(2019, 06, 20, 17, 27, 18, DateTimeKind.Utc), "-", null, 323.358, 1, 0.0),
                    new StockDeal(29846, new DateTime(2019, 06, 20, 17, 33, 34, DateTimeKind.Utc), "+", null, 323.358, 1, 0.0),
                },
                traffic: 9658375.222,
                trafficCount: 29847,
                openInterest: 0,
                status: 1,
                panelJS: 1,
                id: 8553,
                realTime: 0,
                pe2000: 0,
                pe2001: 0,
                closeOneMonth: 326.22,
                closeOneMonthInterval: TimeSpan.FromDays(30),
                closeThreeMonth: 314.85,
                closeThreeMonthInterval: TimeSpan.FromDays(91),
                closeOneYear: 323.91,
                closeOneYearInterval: TimeSpan.FromDays(365),
                oneMonthVolatility: 4.16,
                threeMonthVolatility: 4.20,
                oneYearVolatility: 4.30,
                eps2000: 0,
                eps2001: 0,
                minOneYear: 312.61,
                minOneYearAt: DateTimeOffset.FromUnixTimeSeconds(1553036400).UtcDateTime,
                maxOneYear: 330.76,
                maxOneYearAt: DateTimeOffset.FromUnixTimeSeconds(1530482400).UtcDateTime,
                minAllTimeValue: 227.57,
                minAllTimeAt: DateTimeOffset.FromUnixTimeSeconds(1216591200).UtcDateTime,
                maxAllTimeValue: 330.76,
                maxAllTimeAt: DateTimeOffset.FromUnixTimeSeconds(1530482400).UtcDateTime,
                closeMinOneYear: 313.0590,
                closeMinOneYearAt: DateTimeOffset.FromUnixTimeSeconds(1552950000).UtcDateTime,
                closeMaxOneYear: 330.0765,
                closeMaxOneYearAt: DateTimeOffset.FromUnixTimeSeconds(1530482400).UtcDateTime,
                closeMinAllTimeValue: 228.30,
                closeMinAllTimeAt: DateTimeOffset.FromUnixTimeSeconds(1216332000).UtcDateTime,
                closeMaxAllTimeValue: 330.08,
                closeMaxAllTimeAt: DateTimeOffset.FromUnixTimeSeconds(1530482400).UtcDateTime,
                trafficAvgInSixMonth: 0,
                trafficAvgInOneYear: 0,
                startCount: 0,
                kapit: 0,
                buxKapit: 8419.6,
                changeInOneMonth: -0.88,
                changeInThreeMonth: 2.70,
                changeInOneYear: -0.17,
                startPrice: 0,
                minInOneYear: 0,
                maxInOneYear: 0,
                imageData: new ChartData(
                    DateTimeOffset.FromUnixTimeSeconds(1560981860).UtcDateTime,
                    DateTimeOffset.FromUnixTimeSeconds(1561052024).UtcDateTime,
                    new List<StockPrice>()
                    {
                        new StockPrice(323.32, DateTimeOffset.FromUnixTimeSeconds(1560981860).UtcDateTime, 1),
                        new StockPrice(323.35, DateTimeOffset.FromUnixTimeSeconds(1561052024).UtcDateTime, 1),
                    },
                    "HH:mm"));

            return new ForeignCurrency(
                stock,
                markersID: 8553,
                marketCode: "F",
                dataStart: DateTimeOffset.FromUnixTimeSeconds(1560981600).UtcDateTime,
                dataEnd: DateTimeOffset.FromUnixTimeSeconds(1561067940).UtcDateTime);
        }
    }
}
