using PoLaKoSz.hu.Portfolio_hu_API.Models;
using System;
using System.Collections.Generic;

namespace Library.Tests.Integration.StaticResources.Stocks
{
    class ShareWhenTradingDidNotStartedYet
    {
        public static Share Get()
        {
            var stock = new Stock(
                isStarted: false,
                tickerID: "P_OTP",
                ticker: "OTP",
                type: 1,
                fullName: "OTP",
                prefix: "BET",
                currency: "HUF",
                isin: "HU0000061726",
                name: "OTP",
                shortName: "OTP",
                chartName: "OTP",
                decimals: 0,
                forgDecimals: 0,
                open: 11720,
                close: 11710,
                last: 11500,
                lastHTML: "11 500",
                lastSize: 47769,
                lastTime: DateTimeOffset.FromUnixTimeSeconds(1561475130).UtcDateTime,
                lastHtmlTime: DateTimeOffset.FromUnixTimeSeconds(1561475130).UtcDateTime,
                change: -210,
                changePercentage: -1.79,
                min: 11500,
                max: 11720,
                bid: 0,
                bidSize: 0,
                bidNum: 0,
                bidComp: 0,
                ask: 0,
                askSize: 0,
                askNum: 0,
                askComp: 0,
                bid5: 0,
                bid5Date: DateTimeOffset.FromUnixTimeSeconds(1561475130).UtcDateTime,
                bid5Size: 0,
                bid5Num: 0,
                bid5Comp: 0,
                ask5: 0,
                ask5Date: DateTimeOffset.FromUnixTimeSeconds(1561475130).UtcDateTime,
                ask5Size: 0,
                ask5Num: 0,
                ask5Comp: 0,
                dealsCount: 815,
                deals: new List<StockDeal>()
                {
                    new StockDeal(812, DateTimeOffset.FromUnixTimeSeconds(1561474794).UtcDateTime, " ", " ", 11510, 106, -1.71),
                    new StockDeal(813, DateTimeOffset.FromUnixTimeSeconds(1561474796).UtcDateTime, "+", " ", 11520, 97, -1.62),
                    new StockDeal(814, DateTimeOffset.FromUnixTimeSeconds(1561475130).UtcDateTime, "-", " ", 11500, 47769, -1.79),
                },
                traffic: 6491457190,
                trafficCount: 560734,
                openInterest: 0,
                status: 1,
                panelJS: 1,
                id: 66,
                realTime: 0,
                pe2000: 0,
                pe2001: 0,
                closeOneMonth: 12150,
                closeOneMonthInterval: TimeSpan.FromDays(30),
                closeThreeMonth: 12450,
                closeThreeMonthInterval: TimeSpan.FromDays(91),
                closeOneYear: 9935,
                closeOneYearInterval: TimeSpan.FromDays(365),
                oneMonthVolatility: 19.44,
                threeMonthVolatility: 17.98,
                oneYearVolatility: 21.33,
                eps2000: 0,
                eps2001: 0,
                minOneYear: 9675,
                minOneYearAt: DateTimeOffset.FromUnixTimeSeconds(1537221600).UtcDateTime,
                maxOneYear: 13250,
                maxOneYearAt: DateTimeOffset.FromUnixTimeSeconds(1555279200).UtcDateTime,
                minAllTimeValue: 85,
                minAllTimeAt: DateTimeOffset.FromUnixTimeSeconds(818722800).UtcDateTime,
                maxAllTimeValue: 13250,
                maxAllTimeAt: DateTimeOffset.FromUnixTimeSeconds(1555279200).UtcDateTime,
                closeMinOneYear: 9835,
                closeMinOneYearAt: DateTimeOffset.FromUnixTimeSeconds(1539208800).UtcDateTime,
                closeMaxOneYear: 13230,
                closeMaxOneYearAt: DateTimeOffset.FromUnixTimeSeconds(1555279200).UtcDateTime,
                closeMinAllTimeValue: 85,
                closeMinAllTimeAt: DateTimeOffset.FromUnixTimeSeconds(818722800).UtcDateTime,
                closeMaxAllTimeValue: 13230,
                closeMaxAllTimeAt: DateTimeOffset.FromUnixTimeSeconds(1555279200).UtcDateTime,
                trafficAvgInSixMonth: 12100.5764,
                trafficAvgInOneYear: 11272.3799,
                startCount: 280000010,
                kapit: 3220.000115,
                buxKapit: 8201.6,
                changeInOneMonth: -5.35,
                changeInThreeMonth: -7.63,
                changeInOneYear: 15.75,
                startPrice: 1200,
                minInOneYear: 9675,
                maxInOneYear: 13250,
                imageData: null);

            return new Share(
                stock,
                subGroup: "EQTY_PRIME",
                openTime: TimeSpan.FromHours(9),
                closeTime: TimeSpan.FromHours(17).Add(TimeSpan.FromMinutes(10)),
                market: 1,
                board: "",
                d: 0.469263,
                suly: 0.366923,
                dBumix: 0,
                sulyBumix: 0,
                movingCount: 206360007,
                expire: 0,
                interestRate: 0,
                settlementPercentage: 0,
                indPrice: 11500,
                indPriceAt: DateTimeOffset.FromUnixTimeSeconds(1561475101).UtcDateTime,
                allTimeMin: 85,
                allTimeMax: 13250,
                average: 0,
                symbol: "OTP",
                faceValue: 100,
                faceValueCurrency: "HUF",
                category: "EQTY_PRIME",
                expireAt: "0000-00-00",
                isActive: true,
                lastDate: "2019-06-25",
                lastHtmlDate: "2019-06-25",
                closeDate: "2019-06-24");
        }
    }
}
