using PoLaKoSz.Portfolio.Models;
using System;
using System.Collections.Generic;

namespace PoLaKoSz.Portfolio.Tests.Integration.StaticResources.Stocks
{
    class ShareWithoutBidAsk
    {
        public static Share Get()
        {
            var stock = new Stock(
                isStarted: true,
                tickerID: "P_RABA",
                ticker: "RABA",
                type: 1,
                fullName: "RABA",
                prefix: "BET",
                currency: "HUF",
                isin: "HU0000073457",
                name: "RABA",
                shortName: "RABA",
                chartName: "RABA",
                decimals: 0,
                forgDecimals: 0,
                open: 11720,
                close: 11710,
                last: 11500,
                lastHTML: "11 710",
                lastSize: 47769,
                lastTime: DateTimeOffset.FromUnixTimeSeconds(1561475130).UtcDateTime,
                lastHtmlTime: DateTimeOffset.FromUnixTimeSeconds(1561475130).UtcDateTime,
                change: -210,
                changePercentage: -1.79,
                min: 11500,
                max: 11720,
                bid: 0,
                bidSize: 0,
                bidNum: 0,
                bidComp: 0,
                ask: 0,
                askSize: 0,
                askNum: 0,
                askComp: 0,
                bid5: 0,
                bid5Date: DateTimeOffset.FromUnixTimeSeconds(1561475130).UtcDateTime,
                bid5Size: 0,
                bid5Num: 0,
                bid5Comp: 0,
                ask5: 0,
                ask5Date: DateTimeOffset.FromUnixTimeSeconds(1561475130).UtcDateTime,
                ask5Size: 0,
                ask5Num: 0,
                ask5Comp: 0,
                dealsCount: 815,
                deals: new List<StockDeal>()
                {
                    new StockDeal(615, DateTimeOffset.FromUnixTimeSeconds(1561470204).UtcDateTime, " ", " ", 11500, 25, -1.79),
                    new StockDeal(626, DateTimeOffset.FromUnixTimeSeconds(1561470410).UtcDateTime, "-", " ", 11500, 472, -1.79),
                    new StockDeal(627, DateTimeOffset.FromUnixTimeSeconds(1561470411).UtcDateTime, "+", " ", 11520, 85, -1.62),
                },
                traffic: 6491457190,
                trafficCount: 560734,
                openInterest: 0,
                status: 1,
                panelJS: 1,
                id: 66,
                realTime: 0,
                pe2000: 0,
                pe2001: 0,
                closeOneMonth: 11960,
                closeOneMonthInterval: TimeSpan.FromDays(32),
                closeThreeMonth: 12770,
                closeThreeMonthInterval: TimeSpan.FromDays(91),
                closeOneYear: 9950,
                closeOneYearInterval: TimeSpan.FromDays(365),
                oneMonthVolatility: 19.09,
                threeMonthVolatility: 18.33,
                oneYearVolatility: 21.25,
                eps2000: 0,
                eps2001: 0,
                minOneYear: 9675,
                minOneYearAt: DateTimeOffset.FromUnixTimeSeconds(1537221600).UtcDateTime,
                maxOneYear: 13250,
                maxOneYearAt: DateTimeOffset.FromUnixTimeSeconds(1555279200).UtcDateTime,
                minAllTimeValue: 85,
                minAllTimeAt: DateTimeOffset.FromUnixTimeSeconds(818722800).UtcDateTime,
                maxAllTimeValue: 13250,
                maxAllTimeAt: DateTimeOffset.FromUnixTimeSeconds(1555279200).UtcDateTime,
                closeMinOneYear: 9835,
                closeMinOneYearAt: DateTimeOffset.FromUnixTimeSeconds(1539208800).UtcDateTime,
                closeMaxOneYear: 13230,
                closeMaxOneYearAt: DateTimeOffset.FromUnixTimeSeconds(1555279200).UtcDateTime,
                closeMinAllTimeValue: 85,
                closeMinAllTimeAt: DateTimeOffset.FromUnixTimeSeconds(818722800).UtcDateTime,
                closeMaxAllTimeValue: 13230,
                closeMaxAllTimeAt: DateTimeOffset.FromUnixTimeSeconds(1555279200).UtcDateTime,
                trafficAvgInSixMonth: 12100.6948,
                trafficAvgInOneYear: 11270.8966,
                startCount: 280000010,
                kapit: 3220.000115,
                buxKapit: 8201.6,
                changeInOneMonth: -3.85,
                changeInThreeMonth: -9.95,
                changeInOneYear: 15.58,
                startPrice: 1200,
                minInOneYear: 9675,
                maxInOneYear: 13250,
                imageData: new ChartData(
                    startTime: DateTimeOffset.FromUnixTimeSeconds(1561446025).UtcDateTime,
                    endTime: DateTimeOffset.FromUnixTimeSeconds(1561475130).UtcDateTime,
                    prices: new List<StockPrice>()
                    {
                        new StockPrice(11720, DateTimeOffset.FromUnixTimeSeconds(1561446025).UtcDateTime, 335),
                        new StockPrice(11710, DateTimeOffset.FromUnixTimeSeconds(1561446146).UtcDateTime, 1),
                        new StockPrice(11500, DateTimeOffset.FromUnixTimeSeconds(1561475130).UtcDateTime, 47769),
                    },
                    dateFormat: "HH:mm"));

            return new Share(
                stock,
                subGroup: "EQTY_PRIME",
                openTime: TimeSpan.FromHours(9),
                closeTime: TimeSpan.FromHours(17).Add(TimeSpan.FromMinutes(10)),
                market: 1,
                board: "",
                d: 0.469263,
                suly: 0.366923,
                dBumix: 0,
                sulyBumix: 0,
                movingCount: 206360007,
                expire: 0,
                interestRate: 0,
                settlementPercentage: 0,
                indPrice: 11500,
                indPriceAt: DateTimeOffset.FromUnixTimeSeconds(1561475101).UtcDateTime,
                allTimeMin: 85,
                allTimeMax: 13250,
                average: 0,
                symbol: "RABA",
                faceValue: 100,
                faceValueCurrency: "HUF",
                category: "EQTY_PRIME",
                expireAt: "0000-00-00",
                isActive: true,
                lastDate: "2019-06-24",
                lastHtmlDate: "2019-06-24",
                closeDate: "2019-06-21");
        }
    }
}
